
version: '2'  
services:  
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    container_name: nginx-proxy
    network_mode: bridge
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - '/etc/nginx/vhost.d'
      - '/usr/share/nginx/html'
      - '/etc/nginx/certs:/etc/nginx/certs:ro' 
      - '/var/run/docker.sock:/tmp/docker.sock:ro'

  letsencrypt-nginx-proxy:
    container_name: letsencrypt-nginx-proxy
    image: 'jrcs/letsencrypt-nginx-proxy-companion'
    volumes:
      - '/etc/nginx/certs:/etc/nginx/certs'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    volumes_from:
      - nginx-proxy

  wildfly:
    image: wildfly
    network_mode: bridge
    environment:
     - VIRTUAL_HOST=api.assignapp.nl:8080
     - MYSQL_HOST=***REMOVED***
     - MYSQL_PORT=5306
    ports:
     - '8080:8080'  

networks:
  default:
    external:
      name: nginx-net
