source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.2'

target 'assign-app' do
  use_frameworks!
  # Pods for assign-app
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

end
