version: '2'
services:
  nginx:
    image: assign-page
    restart: always
    network_mode: bridge
    volumes:
      - ./htdocs:/var/www/html
    environment:
      - VIRTUAL_HOST=assignapp.nl

networks:
  default:
    external:
      name: nginx-proxy
