mysql:
  container_name: "db"
  image: mysql:latest
  environment:
    MYSQL_DATABASE: assign
    MYSQL_USER: ***REMOVED***
    MYSQL_PASSWORD: ***REMOVED***
    MYSQL_ROOT_PASSWORD: ***REMOVED***
wildfly:
  image: wildfly
  environment:
    - MYSQL_URI=db:3306
  ports:
    - 8080:8080
  restart: always
  volumes:
    - ./htdocs:/var/www/html
  environment:
    - VIRTUAL_HOST=api.assignapp.nl
